# Generated by Django 3.2.9 on 2021-11-08 10:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, choices=[('', 'Select'), ('Music Production', 'Music Production'), ('Software Development', 'Software Development'), ('Computer Gaming', 'Computer Gaming')], max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('language', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('English', 'English'), ('French', 'French'), ('German', 'German')], max_length=150, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
